server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway    #这个名字是对外暴露的微服务的名字，很重要

eureka:
  client:                                   #表示eureka的客户端，将会注册进eureka服务列表内
    service-url:
    #与eureka服务端配置的地址一致，表示将要入驻到的地址。
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com           #对外暴露的微服务访问地址名  需要映射到host文件中去
    prefer-ip-address: true                 #悬停在微服务名称上可以显示ip地址


info:
  app.name: microservicecloud    #项目名
  company.name: www.yangli.com   #公司名
  build.artifactId: "@project.artifactId@"   #微服务名，动态获取
  build.version: "@project.version@"     #版本号，动态获取